### ISSUE TITLE
Tiny Control Buttons 

### ISSUE THREAD

**Issue by kron05** [justinforce/popout_for_youtube#48]
Hi there!  I wrote about this already on the Google Extension page for YT popout.  For the past 2 weeks I've noticed that the control buttons at the bottom of a popout window are super small. Here's a screenshot of what I'm seeing https://gyazo.com/6b9e21619bb043eb06157615f741092c . I'm running the latest version of El Capitan and Chrome on a Macbook Pro Retina 13 inch laptop with a resolution of 1280x800.  I've tried uninstalling the extension and will try reinstalling chrome all together to see if this helps.  Hope there's a solution to this.

**Comment by justinforce** [comment]
Great news, @kron05! I figured it out! You're zoomed out. Somehow you zoomed out one of your videos, and Chrome remembers that as your zoom preference for the site (extension). So all you have to do to fix it is hit `⌘-0` (Command key plus zero key) on a popped out video to get the default zoom level back.

Please let me know if this fixes it for you!

**Comment by kron05** [comment]
It worked!  Thank you!
