### ISSUE TITLE
Continue playing playlist?

### ISSUE THREAD

**Issue by e0da** [justinforce/popout_for_youtube#5]
"Could you make it so that if you are watching a video from a playlist, it will auto-play the rest of the playlist too?"

**Comment by squeed-server** [comment]
This is an old ticket, but is it still not possible?

If I play a video from a playlist, it won't continue playing, but if I'm picking a playlist from the suggestions afterwards, it will keep on playing that list. Unfortunately for me, this addon is not helpful at all without playlist feature as I want music videos and similar things playing in one section of the screen, and switching manually every 3 minutes or so makes it unusable.

**Comment by armandg** [comment]
I originally came here to request this feature, but saw it had been rejected for API-reasons. Has this changed from 2011 to now? If so, I would like to request this feature.
