### ISSUE TITLE
Have new video open in existing Popout window

### ISSUE THREAD

**Issue by rgilbert1** [justinforce/popout_for_youtube#54]
When a video ends, it'd be nice to be able to click on one of the suggested vids and have it open right there in your existing window, instead of it opening in a new Chrome tab then having to re-pop it out (and in my case at least, have to resize it to fill the spot on my screen I previously had it in).

Side note: I just started using this tool today when I came across it in the Chrome extensions site, and I think it's great! Thanks for making it.

Side note 2: I'm totally down to work on this feature myself, but I've never written let alone read CoffeeScript code, so I'd have to do that first!

**Comment by justinforce** [comment]
Sorry for the incredibly delayed response. This is a hobby project that I return to periodically.

I don't plan to add any playlist support or any complicated logic around opening windows. I think there's a use case for opening multiple windows at the same time (people have told me they do this), and if you introduce window reuse you have to answer the question of when to reuse the window. So I elect to keep it as simple as possible. A clicked button results in a paused video duplicated into a new window, every time. :+1: It's less flexible, but it's easier to understand with no documentation (which nobody reads). It has to be dead simple to be useful.

These are the trade-offs you make in software user interface design. :man_shrugging:
