### ISSUE TITLE
Je ne trouve pas le petit bouton

### ISSUE THREAD

**Issue by ZoneDeTec** [justinforce/popout_for_youtube#57]
Bonjour, pouvez-vous me dire ou se trouve le petit bouton qui sert que la fenêtre s'ouvre 
![capture](https://user-images.githubusercontent.com/31486174/29887537-0acce252-8dbe-11e7-9735-3a1e90ebf88e.PNG)
Merci d'avance

**Comment by justinforce** [comment]
Je vais utiliser Google Translate. Le texte en anglais original est ci-dessous.

Merci beaucoup d'être contacté! Je ne peux pas reproduire cet échec. Lorsque j'ai essayé la même vidéo, je vois le bouton. Veuillez confirmer que l'extension est installée à partir du Chrome Web Store:

https://chrome.google.com/webstore/detail/pofekaindcmmojfnfgbpklepkjfilcep

Bonne chance,
Justin

---

I'll use Google Translate. The original English text is below.

Thank you very much for reaching out! I can't reproduce this failure. When I tried the same video, I see the button. Please confirm that the extension is installed from the Chrome Web Store:

https://chrome.google.com/webstore/detail/pofekaindcmmojfnfgbpklepkjfilcep

Best of luck,
Justin

**Comment by ZoneDeTec** [comment]
Ses bon ! J'ai réussi !
Sa m'aide bcp pour jouer a des jeux en regardant des vidéos !

2017-09-05 2:22 GMT+02:00 Justin Force <notifications@github.com>:
