### ISSUE TITLE
popout always full screen

### ISSUE THREAD

**Issue by bbrys** [justinforce/popout_for_youtube#62]
when I hit the popout button, it goes to nearly full screen and cannot be resized. when I hit full screen, it very slightly goes larder. have removed and reinstalled. just the same.

can you help?

**Comment by justinforce** [comment]
@bbrys and @mjarkk Thank you both for reporting, but I can't reproduce this. The extension is very, very simple. It uses Chrome's API to open a "popup" type window of the same size as the currently playing video. This behavior seems unrelated to this extension.

**Comment by mjarkk** [comment]
@justinforce sinds a while it's possible to scroll in fullscreen that might couse this problem:  
It might be that in you're region this feature isn't rolled out yet

It says in dutch at the bottom: `scroll for details`
![image](https://user-images.githubusercontent.com/15320763/48832946-9e27c680-ed7a-11e8-87b6-025895b2172c.png)
