### ISSUE TITLE
Made the icon look better

### ISSUE THREAD

**Issue by mjarkk** [justinforce/popout_for_youtube#63]
Not that this is a big problem but it looks bit off in a modern website like youtube.  
It would be nice if it has the same style and colors as the YouTube logo

**Comment by justinforce** [comment]
Thank you for taking the time to leave some feedback. If you'd like to contribute new art assets, I'd consider using them. But I'm not very motivated to create anything new myself. And at this point some people have been using this extension for 8 years, and. I don't want to confuse people by changing the interface unless there's a very compelling reason. It's not terribly pretty (I think it did look pretty in 2010 :joy:), but it works how it's supposed to. If it ain't broke, don't fix it.
